spring.application.name=DoAnTotNghiep_LeMinhQuang

# C?u hình Cloudinary
cloudinary.cloud-name=dqlk0ig4c
cloudinary.api-key=591585113685134
cloudinary.api-secret=hRSY00wW6wN1rD9akVqTjwTe3uw

# --- C?U HÌNH DATABASE AIVEN (M?i) ---
# URL: Mình ?ã ghép ?úng Host + Port + DB Name + SSL t? ?nh c?a b?n
spring.datasource.url=jdbc:mysql://mysql-25dc80c5-khanhvu252004-c691.c.aivencloud.com:17480/mylap_db?ssl-mode=REQUIRED

# Username (l?y t? ?nh)
spring.datasource.username=avnadmin

# PASSWORD: Quan tr?ng! B?n quay l?i web Aiven, b?m nút Copy c?nh dòng Password r?i paste vào ?ây
spring.datasource.password=AVNS_CLml1tVE8ceAcb7YJ0-

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# T? ??ng t?o b?ng t? Entity (Product, User...)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- VNPAY CONFIG (?� c?p nh?t th�ng tin th?t) ---
# vnpay.tmn-code=2OERWG67
# vnpay.hash-secret=1VX37LU6GJXFLS94QR6ZBEQ0Y1UWVQFY
# vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
# vnpay.return-url=http://localhost:5173/payment-success

# C?u h�nh m?c ??nh VNPay
# vnpay.version=2.1.0
# vnpay.command=pay
# vnpay.order-type=other

# C?u h�nh AI (Thay m� c?a b?n v�o ch? YOUR_API_KEY)
# gemini.api-key=${AI_KEY}
# # S? d?ng model gemini-2.5-flash (B?n ?n ??nh m?i nh?t hi?n nay)
# gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent